### ISSUE TITLE
Yuzu crashs

### ISSUE THREAD

**Issue by brad38** [maosith/msm-4.19-meow#1]
I saw that zram was tested in the kernel in order to resolve some bugs related to yuzu, I'm a layman when it comes to technical terms, but I noticed significant improvements in terms of random crashes in Yuzu when adjusting some parameters of the "Franco Kernel Manager" app, if you could take a look I hope it helps.. By adjusting these parameters highlighted in the print to 0, I noticed a significant reduction in crashes, perhaps adjusting these values by default in the kernel to low values (not necessarily 0) would present a significant improvement 
![Screenshot_20240205_182423_Franco Kernel Manager](https://github.com/maosith/msm-4.19-meow/assets/68603836/481ba584-94ef-449a-a31b-7e0e88103408)

**Comment by maosith** [comment]
Thank you for feedback.

**Comment by maosith** [comment]
The issue has been solved on lastest tag.
